/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_firmware_revision_string_0     20
#define gattdb_serial_number_string_0         22
#define gattdb_configRWChar                   25
#define gattdb_notifyChar                     27
#define gattdb_battery_level_0                30
#define gattdb_temperature_measurement_0      33
#define gattdb_ota_control                    37


#endif // __GATT_DB_H
